version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Paris
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
    restart: always
